/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeckRouteImport } from './routes/_deck'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DeckIndexRouteImport } from './routes/_deck.index'
import { Route as DeckCaseStudiesRouteImport } from './routes/_deck.case-studies'
import { Route as DeckHowIWorkRouteImport } from './routes/_deck.how-i-work'
import { Route as DeckSayHelloRouteImport } from './routes/_deck.say-hello'
import { Route as DeckWritingRouteImport } from './routes/_deck.writing'
import { Route as CaseStudySlugRouteImport } from './routes/case-study.$slug'
import { Route as ContactEmailRouteImport } from './routes/contact.email'
import { Route as ContactLinkedinRouteImport } from './routes/contact.linkedin'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const DeckRoute = DeckRouteImport.update({
  id: '/_deck',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIndexRoute = DeckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeckRoute,
} as any)
const DeckCaseStudiesRoute = DeckCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => DeckRoute,
} as any)
const DeckHowIWorkRoute = DeckHowIWorkRouteImport.update({
  id: '/how-i-work',
  path: '/how-i-work',
  getParentRoute: () => DeckRoute,
} as any)
const DeckSayHelloRoute = DeckSayHelloRouteImport.update({
  id: '/say-hello',
  path: '/say-hello',
  getParentRoute: () => DeckRoute,
} as any)
const DeckWritingRoute = DeckWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => DeckRoute,
} as any)
const CaseStudySlugRoute = CaseStudySlugRouteImport.update({
  id: '/case-study/$slug',
  path: '/case-study/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactEmailRoute = ContactEmailRouteImport.update({
  id: '/contact/email',
  path: '/contact/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactLinkedinRoute = ContactLinkedinRouteImport.update({
  id: '/contact/linkedin',
  path: '/contact/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeckIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies': typeof DeckCaseStudiesRoute
  '/how-i-work': typeof DeckHowIWorkRoute
  '/say-hello': typeof DeckSayHelloRoute
  '/writing': typeof DeckWritingRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
  '/contact/email': typeof ContactEmailRoute
  '/contact/linkedin': typeof ContactLinkedinRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies': typeof DeckCaseStudiesRoute
  '/how-i-work': typeof DeckHowIWorkRoute
  '/say-hello': typeof DeckSayHelloRoute
  '/writing': typeof DeckWritingRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
  '/contact/email': typeof ContactEmailRoute
  '/contact/linkedin': typeof ContactLinkedinRoute
  '/work/$slug': typeof WorkSlugRoute
  '/': typeof DeckIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_deck': typeof DeckRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_deck/case-studies': typeof DeckCaseStudiesRoute
  '/_deck/how-i-work': typeof DeckHowIWorkRoute
  '/_deck/say-hello': typeof DeckSayHelloRoute
  '/_deck/writing': typeof DeckWritingRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
  '/contact/email': typeof ContactEmailRoute
  '/contact/linkedin': typeof ContactLinkedinRoute
  '/work/$slug': typeof WorkSlugRoute
  '/_deck/': typeof DeckIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/case-studies'
    | '/how-i-work'
    | '/say-hello'
    | '/writing'
    | '/case-study/$slug'
    | '/contact/email'
    | '/contact/linkedin'
    | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/case-studies'
    | '/how-i-work'
    | '/say-hello'
    | '/writing'
    | '/case-study/$slug'
    | '/contact/email'
    | '/contact/linkedin'
    | '/work/$slug'
    | '/'
  id:
    | '__root__'
    | '/_deck'
    | '/sitemap.xml'
    | '/_deck/case-studies'
    | '/_deck/how-i-work'
    | '/_deck/say-hello'
    | '/_deck/writing'
    | '/case-study/$slug'
    | '/contact/email'
    | '/contact/linkedin'
    | '/work/$slug'
    | '/_deck/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeckRoute: typeof DeckRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CaseStudySlugRoute: typeof CaseStudySlugRoute
  ContactEmailRoute: typeof ContactEmailRoute
  ContactLinkedinRoute: typeof ContactLinkedinRoute
  WorkSlugRoute: typeof WorkSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_deck': {
      id: '/_deck'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_deck/': {
      id: '/_deck/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeckIndexRouteImport
      parentRoute: typeof DeckRoute
    }
    '/_deck/case-studies': {
      id: '/_deck/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof DeckCaseStudiesRouteImport
      parentRoute: typeof DeckRoute
    }
    '/_deck/how-i-work': {
      id: '/_deck/how-i-work'
      path: '/how-i-work'
      fullPath: '/how-i-work'
      preLoaderRoute: typeof DeckHowIWorkRouteImport
      parentRoute: typeof DeckRoute
    }
    '/_deck/say-hello': {
      id: '/_deck/say-hello'
      path: '/say-hello'
      fullPath: '/say-hello'
      preLoaderRoute: typeof DeckSayHelloRouteImport
      parentRoute: typeof DeckRoute
    }
    '/_deck/writing': {
      id: '/_deck/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof DeckWritingRouteImport
      parentRoute: typeof DeckRoute
    }
    '/case-study/$slug': {
      id: '/case-study/$slug'
      path: '/case-study/$slug'
      fullPath: '/case-study/$slug'
      preLoaderRoute: typeof CaseStudySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/email': {
      id: '/contact/email'
      path: '/contact/email'
      fullPath: '/contact/email'
      preLoaderRoute: typeof ContactEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/linkedin': {
      id: '/contact/linkedin'
      path: '/contact/linkedin'
      fullPath: '/contact/linkedin'
      preLoaderRoute: typeof ContactLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeckRouteChildren {
  DeckCaseStudiesRoute: typeof DeckCaseStudiesRoute
  DeckHowIWorkRoute: typeof DeckHowIWorkRoute
  DeckSayHelloRoute: typeof DeckSayHelloRoute
  DeckWritingRoute: typeof DeckWritingRoute
  DeckIndexRoute: typeof DeckIndexRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckCaseStudiesRoute: DeckCaseStudiesRoute,
  DeckHowIWorkRoute: DeckHowIWorkRoute,
  DeckSayHelloRoute: DeckSayHelloRoute,
  DeckWritingRoute: DeckWritingRoute,
  DeckIndexRoute: DeckIndexRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeckRoute: DeckRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CaseStudySlugRoute: CaseStudySlugRoute,
  ContactEmailRoute: ContactEmailRoute,
  ContactLinkedinRoute: ContactLinkedinRoute,
  WorkSlugRoute: WorkSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
